"""create models

Revision ID: cc581bb9a81c
Revises: 
Create Date: 2026-03-23 17:52:15.803142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc581bb9a81c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair_tones',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID тона волос (автоинкремент)'),
    sa.Column('tone', sa.String(length=10), nullable=False, comment='Код тона волос (например: 6.0, 6.35, 8.13 - уникальный)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_tones_id'), 'hair_tones', ['id'], unique=False)
    op.create_index(op.f('ix_hair_tones_tone'), 'hair_tones', ['tone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID пользователя (автоинкремент)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Логин продавца (уникальный, макс. 50 символов)'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email продавца для уведомлений (уникальный, макс. 100 символов)'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Захэшированный пароль (bcrypt) для аутентификации'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Флаг главного администратора (True=супер-админ с полными правами)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Телефон продавца для внутренних коммуникаций'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время регистрации продавца в системе'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hair_photos',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID фотографии'),
    sa.Column('tone_id', sa.Integer(), nullable=False, comment='ID тона волос (ForeignKey на hair_tones)'),
    sa.Column('image_url', sa.String(), nullable=False, comment='URL изображения (путь к файлу: /static/photos/6.0-1.jpg)'),
    sa.Column('is_main', sa.Boolean(), nullable=False, comment='Флаг главной фотографии тона (True=показывать первой)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Мягкое удаление фотографии (NULL=активна)'),
    sa.ForeignKeyConstraint(['tone_id'], ['hair_tones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hair_products',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID товара (тон+длина = уникальная позиция)'),
    sa.Column('tone_id', sa.Integer(), nullable=False, comment='ID связанного тона волос (ForeignKey на hair_tones)'),
    sa.Column('length_cm', sa.Integer(), nullable=False, comment='Длина волос в сантиметрах (60, 70, 80, 90...)'),
    sa.Column('purchase_price_per_50g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Цена закупки за 50 грамм (например: 1500.00 руб.)'),
    sa.Column('sale_price_per_50g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Цена продажи за 50 грамм (например: 2500.00 руб.)'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='Ставка налога (доля: 0.2 = 20%, 0.13 = 13%)'),
    sa.Column('stock_grams', sa.Integer(), nullable=False, comment='Общий запас на складе в граммах (всегда >= 0)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Текущее местонахождение товара (warehouse/transit/sold/return_transit)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Мягкое удаление - скрывает товар из списков (NULL=активен)'),
    sa.ForeignKeyConstraint(['tone_id'], ['hair_tones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_products_id'), 'hair_products', ['id'], unique=False)
    op.create_index(op.f('ix_hair_products_length_cm'), 'hair_products', ['length_cm'], unique=False)
    op.create_index(op.f('ix_hair_products_tone_id'), 'hair_products', ['tone_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID заказа (внутренний)'),
    sa.Column('order_number', sa.String(length=20), nullable=False, comment='Уникальный номер заказа для поиска (ORD-2026-00123)'),
    sa.Column('buyer_id', sa.Integer(), nullable=True, comment='ID продавца, создавшего заказ (nullable - внутренние перемещения)'),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True, comment='Телефон клиента (nullable - пока без публичных покупателей)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус заказа: new/confirmed/in_transit/delivered/cancelled'),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Общая сумма заказа с учетом налога'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания заказа'),
    sa.Column('shipper_id', sa.Integer(), nullable=True, comment='ID продавца-отправителя (кто отправил товар)'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Мягкое удаление заказа (NULL=активен)'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID позиции в заказе'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='ID заказа (ForeignKey)'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='ID товара (ForeignKey на hair_products)'),
    sa.Column('grams', sa.Integer(), nullable=False, comment='Количество грамм (50, 100, 150... кратно 50г)'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['hair_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID продажи'),
    sa.Column('order_item_id', sa.Integer(), nullable=False, comment='ID позиции заказа (уникально - 1 позиция = 1 продажа)'),
    sa.Column('seller_id', sa.Integer(), nullable=False, comment='ID продавца, зафиксировавшего продажу'),
    sa.Column('sale_date', sa.DateTime(), nullable=False, comment='Дата фиксации продажи'),
    sa.Column('final_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Итоговая цена продажи с учетом налога'),
    sa.Column('profit', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Прибыль = final_price - (закупка × количество × (1+налог))'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Мягкое удаление продажи (NULL=активна)'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_hair_products_tone_id'), table_name='hair_products')
    op.drop_index(op.f('ix_hair_products_length_cm'), table_name='hair_products')
    op.drop_index(op.f('ix_hair_products_id'), table_name='hair_products')
    op.drop_table('hair_products')
    op.drop_table('hair_photos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hair_tones_tone'), table_name='hair_tones')
    op.drop_index(op.f('ix_hair_tones_id'), table_name='hair_tones')
    op.drop_table('hair_tones')
    # ### end Alembic commands ###
