name: fastapi-hair-prod

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://hair_user:198616Gm@db:5432/hair_db
      - DEBUG=False
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hair_user
      - POSTGRES_PASSWORD=198616Gm
      - POSTGRES_DB=hair_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hair_user -d hair_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  postgres_data: