"""Add order table field descriptns

Revision ID: 3563e54c4973
Revises: 9b4efd6f3d96
Create Date: 2026-07-23 12:13:26.535423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3563e54c4973'
down_revision: Union[str, Sequence[str], None] = '9b4efd6f3d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'description')
    op.add_column('orders', sa.Column('description', sa.String(), nullable=True, comment='Комментарий к заказу'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'description')
    op.add_column('order_items', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Описание позиции'))
    # ### end Alembic commands ###
