"""test3

Revision ID: 4c6d5e174bcd
Revises: c9d2f17f8985
Create Date: 2026-04-01 19:47:14.978044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c6d5e174bcd'
down_revision: Union[str, Sequence[str], None] = 'c9d2f17f8985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hair_products', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор товара',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_products', 'tone_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на оттенок, к которому относится товар',
               existing_nullable=False)
    op.alter_column('hair_products', 'length_cm',
               existing_type=sa.INTEGER(),
               comment='Длина волос в сантиметрах',
               existing_nullable=False)
    op.alter_column('hair_products', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Текущая закупочная цена товара за 100 грамм',
               existing_nullable=False)
    op.alter_column('hair_products', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Текущая цена продажи товара за 100 грамм',
               existing_nullable=False)
    op.alter_column('hair_products', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Налоговая ставка, применяемая к товару',
               existing_nullable=False)
    op.alter_column('hair_products', 'stock_grams',
               existing_type=sa.INTEGER(),
               comment='Текущий остаток товара на складе в граммах',
               existing_nullable=False)
    op.alter_column('hair_products', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Текущий статус товара в системе',
               existing_nullable=False)
    op.alter_column('hair_products', 'booking',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Дата и время бронирования товара, если он зарезервирован',
               existing_nullable=True)
    op.alter_column('hair_tones', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор оттенка волос',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_tones', 'tone',
               existing_type=sa.VARCHAR(length=10),
               comment='Код или название оттенка волос',
               existing_nullable=False)
    op.alter_column('hair_tones', 'photo_url',
               existing_type=sa.VARCHAR(),
               comment='Ссылка на изображение, показывающее данный оттенок волос',
               existing_nullable=True)
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор позиции заказа',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на заказ, к которому относится эта позиция',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на товар, который добавлен в позицию заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'grams',
               existing_type=sa.INTEGER(),
               comment='Количество граммов товара в данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Закупочная цена за 100 грамм на момент оформления позиции',
               existing_nullable=False)
    op.alter_column('order_items', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Цена продажи за 100 грамм в рамках данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'total_sale_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Итоговая стоимость продажи по данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Прибыль, полученная с данной позиции заказа',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный идентификатор заказа',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Уникальный номер заказа в человекочитаемом формате',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Текущий статус заказа',
               existing_nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Общая стоимость заказа до финальных корректировок',
               existing_nullable=True)
    op.alter_column('orders', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Итоговая стоимость заказа после всех изменений и корректировок',
               existing_nullable=True)
    op.alter_column('orders', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Общая прибыль по всему заказу',
               existing_nullable=True)
    op.alter_column('orders', 'seller_id',
               existing_type=sa.INTEGER(),
               comment='Ссылка на пользователя-продавца, ответственного за заказ',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата и время создания заказа',
               existing_nullable=False)
    op.alter_column('orders', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата и время мягкого удаления заказа, если он был удален',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата и время мягкого удаления заказа, если он был удален',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата и время создания заказа',
               existing_nullable=False)
    op.alter_column('orders', 'seller_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на пользователя-продавца, ответственного за заказ',
               existing_nullable=True)
    op.alter_column('orders', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Общая прибыль по всему заказу',
               existing_nullable=True)
    op.alter_column('orders', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Итоговая стоимость заказа после всех изменений и корректировок',
               existing_nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Общая стоимость заказа до финальных корректировок',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Текущий статус заказа',
               existing_nullable=False)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Уникальный номер заказа в человекочитаемом формате',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор заказа',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('order_items', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Прибыль, полученная с данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'total_sale_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Итоговая стоимость продажи по данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Цена продажи за 100 грамм в рамках данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Закупочная цена за 100 грамм на момент оформления позиции',
               existing_nullable=False)
    op.alter_column('order_items', 'grams',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Количество граммов товара в данной позиции заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на товар, который добавлен в позицию заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на заказ, к которому относится эта позиция',
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор позиции заказа',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_tones', 'photo_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Ссылка на изображение, показывающее данный оттенок волос',
               existing_nullable=True)
    op.alter_column('hair_tones', 'tone',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Код или название оттенка волос',
               existing_nullable=False)
    op.alter_column('hair_tones', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор оттенка волос',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_products', 'booking',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Дата и время бронирования товара, если он зарезервирован',
               existing_nullable=True)
    op.alter_column('hair_products', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Текущий статус товара в системе',
               existing_nullable=False)
    op.alter_column('hair_products', 'stock_grams',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Текущий остаток товара на складе в граммах',
               existing_nullable=False)
    op.alter_column('hair_products', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Налоговая ставка, применяемая к товару',
               existing_nullable=False)
    op.alter_column('hair_products', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Текущая цена продажи товара за 100 грамм',
               existing_nullable=False)
    op.alter_column('hair_products', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Текущая закупочная цена товара за 100 грамм',
               existing_nullable=False)
    op.alter_column('hair_products', 'length_cm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Длина волос в сантиметрах',
               existing_nullable=False)
    op.alter_column('hair_products', 'tone_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ссылка на оттенок, к которому относится товар',
               existing_nullable=False)
    op.alter_column('hair_products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный идентификатор товара',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
