"""initial_clean

Revision ID: 4dc56c1a274d
Revises: 
Create Date: 2026-05-01 14:57:58.848748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc56c1a274d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair_tones',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор оттенка волос'),
    sa.Column('tone', sa.String(length=10), nullable=False, comment='Код или название оттенка волос'),
    sa.Column('photo_url', sa.String(), nullable=True, comment='Ссылка на изображение, показывающее данный оттенок волос'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_tones_id'), 'hair_tones', ['id'], unique=False)
    op.create_index(op.f('ix_hair_tones_tone'), 'hair_tones', ['tone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hair_products',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор товара'),
    sa.Column('tone_id', sa.Integer(), nullable=False, comment='Ссылка на оттенок, к которому относится товар'),
    sa.Column('length_cm', sa.Integer(), nullable=False, comment='Длина волос в сантиметрах'),
    sa.Column('purchase_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Текущая закупочная цена товара за 100 грамм'),
    sa.Column('sale_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Текущая цена продажи товара за 100 грамм'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='Налоговая ставка, применяемая к товару'),
    sa.Column('stock_grams', sa.Integer(), nullable=False, comment='Текущий остаток товара на складе в граммах'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Текущий статус товара в системе'),
    sa.Column('booking', sa.DateTime(timezone=True), nullable=True, comment='Дата и время бронирования товара, если он зарезервирован'),
    sa.ForeignKeyConstraint(['tone_id'], ['hair_tones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_products_id'), 'hair_products', ['id'], unique=False)
    op.create_index(op.f('ix_hair_products_length_cm'), 'hair_products', ['length_cm'], unique=False)
    op.create_index(op.f('ix_hair_products_tone_id'), 'hair_products', ['tone_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор заказа'),
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='Уникальный номер заказа в человекочитаемом формате'),
    sa.Column('status', sa.String(length=25), nullable=False, comment='Текущий статус заказа'),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Общая стоимость заказа до финальных корректировок'),
    sa.Column('final_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итоговая стоимость заказа после всех изменений и корректировок'),
    sa.Column('profit', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Общая прибыль по всему заказу'),
    sa.Column('seller_id', sa.Integer(), nullable=True, comment='Ссылка на пользователя-продавца, ответственного за заказ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время создания заказа'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата и время мягкого удаления заказа, если он был удален'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор позиции заказа'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Ссылка на заказ, к которому относится эта позиция'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Ссылка на товар, который добавлен в позицию заказа'),
    sa.Column('grams', sa.Integer(), nullable=False, comment='Количество граммов товара в данной позиции заказа'),
    sa.Column('purchase_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Закупочная цена за 100 грамм на момент оформления позиции'),
    sa.Column('sale_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='цена продажи за 100 грамм на момент оформления позиции'),
    sa.Column('total_sale_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='итоговая сумма продажи именно по этой позиции: grams × sale_price_per_100g/100'),
    sa.Column('profit', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='прибыль по этой позиции: '),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['hair_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_hair_products_tone_id'), table_name='hair_products')
    op.drop_index(op.f('ix_hair_products_length_cm'), table_name='hair_products')
    op.drop_index(op.f('ix_hair_products_id'), table_name='hair_products')
    op.drop_table('hair_products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hair_tones_tone'), table_name='hair_tones')
    op.drop_index(op.f('ix_hair_tones_id'), table_name='hair_tones')
    op.drop_table('hair_tones')
    # ### end Alembic commands ###
