"""change created_at to Moscow timezone

Revision ID: 7ff1a82eb6a7
Revises: f38823e853d3
Create Date: 2026-06-26 20:23:07.538243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff1a82eb6a7'
down_revision: Union[str, Sequence[str], None] = 'f38823e853d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
