"""Add customers table field description

Revision ID: 9b4efd6f3d96
Revises: 07365d9b2bdc
Create Date: 2026-07-23 12:08:47.046487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4efd6f3d96'
down_revision: Union[str, Sequence[str], None] = '07365d9b2bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('description', sa.String(), nullable=True, comment='Описание позиции'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'description')
    # ### end Alembic commands ###
