"""test2

Revision ID: c9d2f17f8985
Revises: eace81a41a3a
Create Date: 2026-04-01 17:00:30.867884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9d2f17f8985'
down_revision: Union[str, Sequence[str], None] = 'eace81a41a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hair_products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID товара (тон+длина)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_products', 'tone_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID тона',
               existing_nullable=False)
    op.alter_column('hair_products', 'length_cm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Длина см (60, 70, 80...)',
               existing_nullable=False)
    op.alter_column('hair_products', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Цена закупки за 100г',
               existing_nullable=False)
    op.alter_column('hair_products', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Оптимальная цена продажи за 100г',
               existing_nullable=False)
    op.alter_column('hair_products', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Налог (0.2=20%)',
               existing_nullable=False)
    op.alter_column('hair_products', 'stock_grams',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Запас грамм',
               existing_nullable=False)
    op.alter_column('hair_products', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='warehouse/transit/sold/return_transit',
               existing_nullable=False)
    op.alter_column('hair_products', 'booking',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Бронь до даты',
               existing_nullable=True)
    op.alter_column('hair_tones', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID тона',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_tones', 'tone',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Код тона (6.0, 6.35, 8.13)',
               existing_nullable=False)
    op.alter_column('hair_tones', 'photo_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL главной фото тона',
               existing_nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID заказа',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Товар (тон+длина)',
               existing_nullable=False)
    op.alter_column('order_items', 'grams',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Сколько грамм этого товара в заказе',
               existing_nullable=False)
    op.alter_column('order_items', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Цена закупки на момент продажи',
               existing_nullable=False)
    op.alter_column('order_items', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Цена продажи за 100г',
               existing_nullable=False)
    op.alter_column('order_items', 'total_sale_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='грамм * цена за 100г / 100',
               existing_nullable=False)
    op.alter_column('order_items', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='общая прибыль по строке',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID заказа',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='ORD-2026-00123',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='in_transit/delivered/cancelled/returned',
               existing_nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Сумма заказа',
               existing_nullable=True)
    op.alter_column('orders', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Итог продажи, заполняется при продаже для фиксации прибыли',
               existing_nullable=True)
    op.alter_column('orders', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Прибыль',
               existing_nullable=True)
    op.alter_column('orders', 'seller_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Кто продал',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Создан',
               existing_nullable=False)
    op.alter_column('orders', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Мягкое удаление',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уникальный ID пользователя (автоинкремент)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Логин продавца (уникальный, макс. 50 символов)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Email продавца для уведомлений (уникальный, макс. 100 символов)',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Захэшированный пароль (bcrypt) для аутентификации',
               existing_nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Флаг главного администратора (True=супер-админ с полными правами)',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Телефон продавца для внутренних коммуникаций',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата и время регистрации продавца в системе',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата и время регистрации продавца в системе',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Телефон продавца для внутренних коммуникаций',
               existing_nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment='Флаг главного администратора (True=супер-админ с полными правами)',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='Захэшированный пароль (bcrypt) для аутентификации',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               comment='Email продавца для уведомлений (уникальный, макс. 100 символов)',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Логин продавца (уникальный, макс. 50 символов)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='Уникальный ID пользователя (автоинкремент)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Мягкое удаление',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Создан',
               existing_nullable=False)
    op.alter_column('orders', 'seller_id',
               existing_type=sa.INTEGER(),
               comment='Кто продал',
               existing_nullable=True)
    op.alter_column('orders', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Прибыль',
               existing_nullable=True)
    op.alter_column('orders', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Итог продажи, заполняется при продаже для фиксации прибыли',
               existing_nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Сумма заказа',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='in_transit/delivered/cancelled/returned',
               existing_nullable=False)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               comment='ORD-2026-00123',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment='ID заказа',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('order_items', 'profit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='общая прибыль по строке',
               existing_nullable=False)
    op.alter_column('order_items', 'total_sale_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='грамм * цена за 100г / 100',
               existing_nullable=False)
    op.alter_column('order_items', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Цена продажи за 100г',
               existing_nullable=False)
    op.alter_column('order_items', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Цена закупки на момент продажи',
               existing_nullable=False)
    op.alter_column('order_items', 'grams',
               existing_type=sa.INTEGER(),
               comment='Сколько грамм этого товара в заказе',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='Товар (тон+длина)',
               existing_nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment='ID заказа',
               existing_nullable=False)
    op.alter_column('hair_tones', 'photo_url',
               existing_type=sa.VARCHAR(),
               comment='URL главной фото тона',
               existing_nullable=True)
    op.alter_column('hair_tones', 'tone',
               existing_type=sa.VARCHAR(length=10),
               comment='Код тона (6.0, 6.35, 8.13)',
               existing_nullable=False)
    op.alter_column('hair_tones', 'id',
               existing_type=sa.INTEGER(),
               comment='ID тона',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hair_products', 'booking',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Бронь до даты',
               existing_nullable=True)
    op.alter_column('hair_products', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='warehouse/transit/sold/return_transit',
               existing_nullable=False)
    op.alter_column('hair_products', 'stock_grams',
               existing_type=sa.INTEGER(),
               comment='Запас грамм',
               existing_nullable=False)
    op.alter_column('hair_products', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Налог (0.2=20%)',
               existing_nullable=False)
    op.alter_column('hair_products', 'sale_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Оптимальная цена продажи за 100г',
               existing_nullable=False)
    op.alter_column('hair_products', 'purchase_price_per_100g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Цена закупки за 100г',
               existing_nullable=False)
    op.alter_column('hair_products', 'length_cm',
               existing_type=sa.INTEGER(),
               comment='Длина см (60, 70, 80...)',
               existing_nullable=False)
    op.alter_column('hair_products', 'tone_id',
               existing_type=sa.INTEGER(),
               comment='ID тона',
               existing_nullable=False)
    op.alter_column('hair_products', 'id',
               existing_type=sa.INTEGER(),
               comment='ID товара (тон+длина)',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
