"""test

Revision ID: eace81a41a3a
Revises: af054f738a9b
Create Date: 2026-03-30 18:09:29.969881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eace81a41a3a'
down_revision: Union[str, Sequence[str], None] = 'af054f738a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair_tones',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID тона'),
    sa.Column('tone', sa.String(length=10), nullable=False, comment='Код тона (6.0, 6.35, 8.13)'),
    sa.Column('photo_url', sa.String(), nullable=True, comment='URL главной фото тона'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_tones_id'), 'hair_tones', ['id'], unique=False)
    op.create_index(op.f('ix_hair_tones_tone'), 'hair_tones', ['tone'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный ID пользователя (автоинкремент)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Логин продавца (уникальный, макс. 50 символов)'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email продавца для уведомлений (уникальный, макс. 100 символов)'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Захэшированный пароль (bcrypt) для аутентификации'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Флаг главного администратора (True=супер-админ с полными правами)'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Телефон продавца для внутренних коммуникаций'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время регистрации продавца в системе'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hair_products',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID товара (тон+длина)'),
    sa.Column('tone_id', sa.Integer(), nullable=False, comment='ID тона'),
    sa.Column('length_cm', sa.Integer(), nullable=False, comment='Длина см (60, 70, 80...)'),
    sa.Column('purchase_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Цена закупки за 100г'),
    sa.Column('sale_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Оптимальная цена продажи за 100г'),
    sa.Column('tax_rate', sa.Float(), nullable=False, comment='Налог (0.2=20%)'),
    sa.Column('stock_grams', sa.Integer(), nullable=False, comment='Запас грамм'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='warehouse/transit/sold/return_transit'),
    sa.Column('booking', sa.DateTime(timezone=True), nullable=True, comment='Бронь до даты'),
    sa.ForeignKeyConstraint(['tone_id'], ['hair_tones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_products_id'), 'hair_products', ['id'], unique=False)
    op.create_index(op.f('ix_hair_products_length_cm'), 'hair_products', ['length_cm'], unique=False)
    op.create_index(op.f('ix_hair_products_tone_id'), 'hair_products', ['tone_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID заказа'),
    sa.Column('order_number', sa.String(length=20), nullable=False, comment='ORD-2026-00123'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='in_transit/delivered/cancelled/returned'),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Сумма заказа'),
    sa.Column('final_price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Итог продажи, заполняется при продаже для фиксации прибыли'),
    sa.Column('profit', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Прибыль'),
    sa.Column('seller_id', sa.Integer(), nullable=True, comment='Кто продал'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Создан'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Мягкое удаление'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='ID заказа'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Товар (тон+длина)'),
    sa.Column('grams', sa.Integer(), nullable=False, comment='Сколько грамм этого товара в заказе'),
    sa.Column('purchase_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Цена закупки на момент продажи'),
    sa.Column('sale_price_per_100g', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Цена продажи за 100г'),
    sa.Column('total_sale_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='грамм * цена за 100г / 100'),
    sa.Column('profit', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='общая прибыль по строке'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['hair_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_hair_products_tone_id'), table_name='hair_products')
    op.drop_index(op.f('ix_hair_products_length_cm'), table_name='hair_products')
    op.drop_index(op.f('ix_hair_products_id'), table_name='hair_products')
    op.drop_table('hair_products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hair_tones_tone'), table_name='hair_tones')
    op.drop_index(op.f('ix_hair_tones_id'), table_name='hair_tones')
    op.drop_table('hair_tones')
    # ### end Alembic commands ###
