"""refactoring models

Revision ID: f38823e853d3
Revises: 84c3e2bf9616
Create Date: 2026-06-17 15:53:33.652575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f38823e853d3'
down_revision: Union[str, Sequence[str], None] = '84c3e2bf9616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('wallet_transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_wallet_transactions_created_by_user'), table_name='wallet_transactions')
    op.create_index('ix_transactions_user_created', 'wallet_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'wallet_transactions', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('wallet_transactions', 'created_by_user')
    op.add_column('wallets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index('ix_wallets_user_balance', 'wallets', ['user_id', 'balance'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index('ix_wallets_user_balance', table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_column('wallets', 'user_id')
    op.add_column('wallet_transactions', sa.Column('created_by_user', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index('ix_transactions_user_created', table_name='wallet_transactions')
    op.create_index(op.f('ix_wallet_transactions_created_by_user'), 'wallet_transactions', ['created_by_user'], unique=False)
    op.drop_column('wallet_transactions', 'user_id')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
